== What is this?

This is a proof of concept integrating Spring Cloud technologies for building an API Gateway solution.

It illustrates the following use cases:

* Routing of HTTP requests to a RESTful component;
* Claim checking of incoming data based on request payload;
* Routing of HTTP requests to a messaging system;
* Event-driven processing of forwarded HTTP requests as part of a multi-stage pipeline;
* Status checking of pending requests;
* Dynamic service registration via Eureka

== Components

The project consists of the following modules:

* link:config-server[`config-server`] - a Config Server for hosting configuration from a git repository at `/tmp/config-repo`
* link:eureka-server[`eureka-server`] - a Eureka Service Registry
* link:gateway[`gateway`] - a Zuul gateway with custom filters for claim checking and XPath header enrichment, supporting routing to both static applications and dynamically registered applications via Eureka;
* link:message-dispatcher[`message-dispatcher`] - a Spring Cloud Stream application that routes http requests to the various queues;
  the application is statically registered in the Zuul gateway;
* link:xslt-processor[`xslt-processor`] - a Spring Cloud Stream application that transforms messages by delegating to an XSL stylesheet;
* link:order-status[`order-status`] - a RESTful application that displays the status of a request as it is handled by the system.

== Prerequisites

The project requires a running RabbitMQ Server listening on port 5672 on localhost.

== Building and running

The project can be built with Maven.

    $ mvn clean package

Start the component modules:

    $ ./start-all.sh

The applications are registered to the following ports:

* `config-server`: 8888
* `eureka-server`: 8761
* `gateway`: 8080
* `message-dispatcher`: 9000
* `order-status`: 8090

The application logs are available within the `logs` directory.

The application PIDs are all written to `logs/pids`.

The applications can be stopped by executing `stop-all.sh`.

The stream processing pipeline can be deployed using Spring Cloud Data Flow.
Start the Data Flow Server and then execute the following commands in the shell:

```
dataflow:> app import --uri http://bit.ly/1-0-4-GA-stream-applications-rabbit-maven

dataflow:> app register --name xslt --type processor --uri file:///<path-to-project>/xslt-processor/target/xslt-processor-1.0.0.BUILD-SNAPSHOT.jar

dataflow:> stream create orders --definition ":orders.input > pricer: xslt --xslt.stylesheet=file:///<path-to-project>/resources/add-price.xsl | taxer: xslt --xslt.stylesheet=file:///<path-to-project>/resources/calc-tax.xsl | log" --deploy

dataflow:> stream create accepted-status --definition ":orders.input > :orders.status" --deploy

dataflow:> stream create price-status --definition ":orders.pricer > :orders.status" --deploy

dataflow:> stream create tax-status --definition ":orders.taxer > :orders.status" --deploy
```

Open the form `upload.html` in a web browser and upload the `simple-order.xml` file.

The form will upload the contents of the file to the `http://localhost:8080/messages/orders` endpoint as a multipart form.

Once the file is uploaded it will be processed first by `pricer`,
and after the first processor is done and has sent its notification message, by `taxer`.
Finally it will arrive at the `log` sink where the output will be similar to the following:

```
2016-11-16 12:32:48.164  INFO 41871 --- [.taxer.orders-1] log.sink:
<?xml version="1.0" encoding="UTF-8"?>
<order customer="acme" id="00000000-0000-0000-0000-000000000001">
  <item type="widget" quantity="42" price="224.70000000000002"/>
</order>
```

As shown above, the ID (generated during the claim-check) has been added as well as the price (by the `pricer` app).
The price was then replaced after tax was calculated by the `taxer` app.

You can use the `http://localhost:8080/orders/status/${order-id}` URL to check the status of an order as it progresses.
Use the same order id as displayed in the log output as shown above. For example:

```
$ curl :8080/orders/status/00000000-0000-0000-0000-000000000001
accepted,priced,taxed
```

Currently both `pricer` and `taxer` have a 10 second delay to simulate processing time.
If you check the status within each 10 second window, you will see each of the above
phases accumulating in the status response.

Watch this page as the solution continues to evolve...
(XPath header enrichment, config-server with dynamic updates, tracing, etc.)
