== What is this?

This is a proof of concept integrating Spring Cloud technologies for building an API Gateway solution.

It illustrates the following use cases:

* Routing of HTTP requests to a RESTful component;
* Claim checking of incoming data based on request payload;
* Routing of HTTP requests to a messaging system;
* Event-driven processing of forwarded HTTP requests as part of a multi-stage pipeline;
* Status checking of pending requests;
* Dynamic service registration via Eureka

== Components

The project consists of the following modules:

* link:config-server[`config-server`] - a Config Server for hosting configuration from a git repository at `/tmp/config-repo`
* link:eureka-server[`eureka-server`] - a Eureka Service Registry
* link:gateway[`gateway`] - a Zuul gateway with custom filters for claim checking and XPath header enrichment, supporting routing to both static applications and dynamically registered applications via Eureka;
* link:message-dispatcher[`message-dispatcher`] - a Spring Cloud Stream application that routes http requests to the various queues;
  the application is statically registered in the Zuul gateway;
* link:order-processor[`order-processor`] - a Spring Cloud Stream application that processes messages sent by the dispatcher;
* link:order-phase2[`order-phase2`] - a Spring Cloud Stream application that processes messages sent by the `order-processor`;
* link:order-status[`order-status`] - a RESTful application that displays the status of a request as it is handled by the system.

== Prerequisites

The project requires a running RabbitMQ Server listening on port 5672 on localhost.

== Building and running

The project can be built with Maven.

    $ mvn clean package

Start the component modules:

    $ ./start-all.sh

The applications are registered to the following ports:

* `config-server`: 8888
* `eureka-server`: 8761
* `gateway`: 8080
* `message-dispatcher`: 9000
* `order-processor`: 9001
* `order-phase2`: 9002
* `order-status`: 8090

The application logs are available within the `logs` directory.

The application PIDs are all written to `logs/pids`.

The applications can be stopped by executing `stop-all.sh`.

Open the form `upload.html` in a web browser and upload the `simple-order.xml` file.

The form will upload the contents of the file to the `http://localhost:8080/messages/orders` endpoint as a multipart form.

Once the file is uploaded it will be processed first by `order-processor`,
and after the first processor is done and has sent its notification message, by `order-phase2`.

Expect some output similar to the following in the log of the `order-processor` application:

    2016-10-31 01:18:09.810  INFO 15491 --- [MmO6M0Jooo1Fw-1] i.p.e.o.p.OrderProcessorConfiguration    : received order with payload: {order=00000000-0000-0000-0000-000000000001}, and headers: {..}
    2016-10-31 01:18:39.813  INFO 15491 --- [MmO6M0Jooo1Fw-1] i.p.e.o.p.OrderProcessorConfiguration    : processing order: /tmp/uploads/00000000-0000-0000-0000-000000000001.pending

The `order-processor` waits 30 seconds before updating the extension of the file to `pending`.
You can use the `http://localhost:8080/orders/status/${order-id}` URL to check the status of an order as it progresses.
Use the same order-id as displayed in the log output as shown above.

Expect some output similar to the following in the log of the `order-phase2` application:

    2016-10-31 01:18:39.844  INFO 15777 --- [ZafWknlBvznJQ-1] .e.o.p.OrderProcessorPhase2Configuration : received order: /tmp/uploads/00000000-0000-0000-0000-000000000001
    2016-10-31 01:19:09.846  INFO 15777 --- [    scheduler-1] .e.o.p.OrderProcessorPhase2Configuration : processing order: /tmp/uploads/00000000-0000-0000-0000-000000000001.phase2

Watch this page as the solution continues to evolve...
(XPath header enrichment, XSLT processing, etc.)
